"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
---------------------------------------------------------------------
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class SampleMeasurementParameter(google.protobuf.message.Message):
    """---------------------------------------------------------------------
    ---------------------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FLOAT_IN_FIELD_NUMBER: builtins.int
    DOUBLE_ARRAY_IN_FIELD_NUMBER: builtins.int
    BOOL_IN_FIELD_NUMBER: builtins.int
    STRING_IN_FIELD_NUMBER: builtins.int
    STRING_ARRAY_IN_FIELD_NUMBER: builtins.int
    float_in: builtins.float
    @property
    def double_array_in(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    bool_in: builtins.bool
    string_in: builtins.str
    @property
    def string_array_in(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        float_in: builtins.float = ...,
        double_array_in: collections.abc.Iterable[builtins.float] | None = ...,
        bool_in: builtins.bool = ...,
        string_in: builtins.str = ...,
        string_array_in: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "bool_in",
            b"bool_in",
            "double_array_in",
            b"double_array_in",
            "float_in",
            b"float_in",
            "string_array_in",
            b"string_array_in",
            "string_in",
            b"string_in",
        ],
    ) -> None: ...

global___SampleMeasurementParameter = SampleMeasurementParameter
