# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample_measurement_test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x1dsample_measurement_test.proto\x12'ni.measurementlink.measurement.tests.v1\"\x84\x01\n\x1aSampleMeasurementParameter\x12\x10\n\x08\x66loat_in\x18\x01 \x01(\x02\x12\x17\n\x0f\x64ouble_array_in\x18\x02 \x03(\x01\x12\x0f\n\x07\x62ool_in\x18\x03 \x01(\x08\x12\x11\n\tstring_in\x18\x04 \x01(\t\x12\x17\n\x0fstring_array_in\x18\x05 \x03(\tB7\xaa\x02\x34NationalInstruments.MeasurementServices.Measurementsb\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "sample_measurement_test_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\252\0024NationalInstruments.MeasurementServices.Measurements"
    )
    _SAMPLEMEASUREMENTPARAMETER._serialized_start = 75
    _SAMPLEMEASUREMENTPARAMETER._serialized_end = 207
# @@protoc_insertion_point(module_scope)
