# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\x12\x17\x65xternal_driver_wrapper\"d\n\x11InitializeRequest\x12\x15\n\rresource_name\x18\x01 \x01(\t\x12\x10\n\x08id_query\x18\x02 \x01(\x08\x12\x14\n\x0creset_device\x18\x03 \x01(\x08\x12\x10\n\x08simulate\x18\x04 \x01(\x08\",\n\x12InitializeResponse\x12\x16\n\x0eis_initialized\x18\x01 \x01(\x08\"_\n!ConfigureMeasurementDigitsRequest\x12\x10\n\x08\x66unction\x18\x01 \x01(\x05\x12\r\n\x05range\x18\x02 \x01(\x01\x12\x19\n\x11resolution_digits\x18\x03 \x01(\x01\"$\n\"ConfigureMeasurementDigitsResponse\"\r\n\x0bReadRequest\"\x1d\n\x0cReadResponse\x12\r\n\x05value\x18\x01 \x01(\x01\"\x0e\n\x0c\x43loseRequest\"\x0f\n\rCloseResponse2\xc3\x03\n\x15InstrumentInteraction\x12\x65\n\nInitialize\x12*.external_driver_wrapper.InitializeRequest\x1a+.external_driver_wrapper.InitializeResponse\x12\x95\x01\n\x1a\x43onfigureMeasurementDigits\x12:.external_driver_wrapper.ConfigureMeasurementDigitsRequest\x1a;.external_driver_wrapper.ConfigureMeasurementDigitsResponse\x12S\n\x04Read\x12$.external_driver_wrapper.ReadRequest\x1a%.external_driver_wrapper.ReadResponse\x12V\n\x05\x43lose\x12%.external_driver_wrapper.CloseRequest\x1a&.external_driver_wrapper.CloseResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INITIALIZEREQUEST._serialized_start=41
  _INITIALIZEREQUEST._serialized_end=141
  _INITIALIZERESPONSE._serialized_start=143
  _INITIALIZERESPONSE._serialized_end=187
  _CONFIGUREMEASUREMENTDIGITSREQUEST._serialized_start=189
  _CONFIGUREMEASUREMENTDIGITSREQUEST._serialized_end=284
  _CONFIGUREMEASUREMENTDIGITSRESPONSE._serialized_start=286
  _CONFIGUREMEASUREMENTDIGITSRESPONSE._serialized_end=322
  _READREQUEST._serialized_start=324
  _READREQUEST._serialized_end=337
  _READRESPONSE._serialized_start=339
  _READRESPONSE._serialized_end=368
  _CLOSEREQUEST._serialized_start=370
  _CLOSEREQUEST._serialized_end=384
  _CLOSERESPONSE._serialized_start=386
  _CLOSERESPONSE._serialized_end=401
  _INSTRUMENTINTERACTION._serialized_start=404
  _INSTRUMENTINTERACTION._serialized_end=855
# @@protoc_insertion_point(module_scope)
