version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      - pip install poetry==1.8.2
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs
      working-directory: packages/service

sphinx:
  configuration: packages/service/_docs_source/conf.py