"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import ni_measurement_plugin_sdk_service._internal.stubs.ni.protobuf.types.xydata_pb2 as ni_protobuf_types_xydata_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DifferentColor:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DifferentColorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DifferentColor.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PURPLE: _DifferentColor.ValueType  # 0
    ORANGE: _DifferentColor.ValueType  # 1
    TEAL: _DifferentColor.ValueType  # 2
    BROWN: _DifferentColor.ValueType  # 3

class DifferentColor(_DifferentColor, metaclass=_DifferentColorEnumTypeWrapper): ...

PURPLE: DifferentColor.ValueType  # 0
ORANGE: DifferentColor.ValueType  # 1
TEAL: DifferentColor.ValueType  # 2
BROWN: DifferentColor.ValueType  # 3
global___DifferentColor = DifferentColor

class _Countries:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CountriesEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Countries.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    AMERICA: _Countries.ValueType  # 0
    TAIWAN: _Countries.ValueType  # 1
    AUSTRALIA: _Countries.ValueType  # 2
    CANADA: _Countries.ValueType  # 3

class Countries(_Countries, metaclass=_CountriesEnumTypeWrapper): ...

AMERICA: Countries.ValueType  # 0
TAIWAN: Countries.ValueType  # 1
AUSTRALIA: Countries.ValueType  # 2
CANADA: Countries.ValueType  # 3
global___Countries = Countries

@typing.final
class MeasurementParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FLOAT_DATA_FIELD_NUMBER: builtins.int
    DOUBLE_DATA_FIELD_NUMBER: builtins.int
    INT32_DATA_FIELD_NUMBER: builtins.int
    UINT32_DATA_FIELD_NUMBER: builtins.int
    INT64_DATA_FIELD_NUMBER: builtins.int
    UINT64_DATA_FIELD_NUMBER: builtins.int
    BOOL_DATA_FIELD_NUMBER: builtins.int
    STRING_DATA_FIELD_NUMBER: builtins.int
    DOUBLE_ARRAY_DATA_FIELD_NUMBER: builtins.int
    FLOAT_ARRAY_DATA_FIELD_NUMBER: builtins.int
    INT32_ARRAY_DATA_FIELD_NUMBER: builtins.int
    UINT32_ARRAY_DATA_FIELD_NUMBER: builtins.int
    INT64_ARRAY_DATA_FIELD_NUMBER: builtins.int
    UINT64_ARRAY_DATA_FIELD_NUMBER: builtins.int
    BOOL_ARRAY_DATA_FIELD_NUMBER: builtins.int
    STRING_ARRAY_DATA_FIELD_NUMBER: builtins.int
    ENUM_DATA_FIELD_NUMBER: builtins.int
    ENUM_ARRAY_DATA_FIELD_NUMBER: builtins.int
    INT_ENUM_DATA_FIELD_NUMBER: builtins.int
    INT_ENUM_ARRAY_DATA_FIELD_NUMBER: builtins.int
    XY_DATA_FIELD_NUMBER: builtins.int
    XY_DATA_ARRAY_FIELD_NUMBER: builtins.int
    float_data: builtins.float
    double_data: builtins.float
    int32_data: builtins.int
    uint32_data: builtins.int
    int64_data: builtins.int
    uint64_data: builtins.int
    bool_data: builtins.bool
    string_data: builtins.str
    enum_data: global___DifferentColor.ValueType
    int_enum_data: global___Countries.ValueType
    @property
    def double_array_data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def float_array_data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def int32_array_data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def uint32_array_data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def int64_array_data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def uint64_array_data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def bool_array_data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bool]: ...
    @property
    def string_array_data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def enum_array_data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___DifferentColor.ValueType]: ...
    @property
    def int_enum_array_data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___Countries.ValueType]: ...
    @property
    def xy_data(self) -> ni_protobuf_types_xydata_pb2.DoubleXYData: ...
    @property
    def xy_data_array(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ni_protobuf_types_xydata_pb2.DoubleXYData]: ...
    def __init__(
        self,
        *,
        float_data: builtins.float = ...,
        double_data: builtins.float = ...,
        int32_data: builtins.int = ...,
        uint32_data: builtins.int = ...,
        int64_data: builtins.int = ...,
        uint64_data: builtins.int = ...,
        bool_data: builtins.bool = ...,
        string_data: builtins.str = ...,
        double_array_data: collections.abc.Iterable[builtins.float] | None = ...,
        float_array_data: collections.abc.Iterable[builtins.float] | None = ...,
        int32_array_data: collections.abc.Iterable[builtins.int] | None = ...,
        uint32_array_data: collections.abc.Iterable[builtins.int] | None = ...,
        int64_array_data: collections.abc.Iterable[builtins.int] | None = ...,
        uint64_array_data: collections.abc.Iterable[builtins.int] | None = ...,
        bool_array_data: collections.abc.Iterable[builtins.bool] | None = ...,
        string_array_data: collections.abc.Iterable[builtins.str] | None = ...,
        enum_data: global___DifferentColor.ValueType = ...,
        enum_array_data: collections.abc.Iterable[global___DifferentColor.ValueType] | None = ...,
        int_enum_data: global___Countries.ValueType = ...,
        int_enum_array_data: collections.abc.Iterable[global___Countries.ValueType] | None = ...,
        xy_data: ni_protobuf_types_xydata_pb2.DoubleXYData | None = ...,
        xy_data_array: collections.abc.Iterable[ni_protobuf_types_xydata_pb2.DoubleXYData] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["xy_data", b"xy_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bool_array_data", b"bool_array_data", "bool_data", b"bool_data", "double_array_data", b"double_array_data", "double_data", b"double_data", "enum_array_data", b"enum_array_data", "enum_data", b"enum_data", "float_array_data", b"float_array_data", "float_data", b"float_data", "int32_array_data", b"int32_array_data", "int32_data", b"int32_data", "int64_array_data", b"int64_array_data", "int64_data", b"int64_data", "int_enum_array_data", b"int_enum_array_data", "int_enum_data", b"int_enum_data", "string_array_data", b"string_array_data", "string_data", b"string_data", "uint32_array_data", b"uint32_array_data", "uint32_data", b"uint32_data", "uint64_array_data", b"uint64_array_data", "uint64_data", b"uint64_data", "xy_data", b"xy_data", "xy_data_array", b"xy_data_array"]) -> None: ...

global___MeasurementParameter = MeasurementParameter
