#!/usr/bin/env python3
"""Generates gRPC Python stubs from proto files."""

import pathlib
import shutil
from collections.abc import Sequence

import grpc_tools.protoc
import pkg_resources

STUBS_NAMESPACE = "ni_measurement_plugin_sdk_service._internal.stubs"
PROTO_PARENT_NAMESPACES = ["ni.measurementlink", "nidevice_grpc", "ni.protobuf.types"]
STUBS_PATH = pathlib.Path(__file__).parent.parent / STUBS_NAMESPACE.replace(".", "/")
PROTO_PATH = pathlib.Path(__file__).parent.parent.parent.parent / "third_party" / "ni-apis"
STUBS_PROTO_PATH = STUBS_PATH / "proto"
STUBS_PROTO_FILES = list(STUBS_PROTO_PATH.rglob("*.proto"))
# We still want to use session.proto from STUBS_PATH / "proto" until
# we can upgrade in sync with nimi-python and nidaqmx-python
# AB#2730545
GRPC_DEVICE_PROTO_PATH = PROTO_PATH / "ni" / "grpcdevice" / "v1"
NI_API_PROTO_FILES = list(
    path for path in PROTO_PATH.rglob("*.proto") if not path.is_relative_to(GRPC_DEVICE_PROTO_PATH)
)

TEST_STUBS_PATH = pathlib.Path(__file__).parent.parent / "tests" / "utilities" / "stubs"
TEST_PROTO_PATH = TEST_STUBS_PATH
TEST_PROTO_FILES = list(TEST_PROTO_PATH.rglob("*.proto"))


def main():
    """Generate and fixup gRPC Python stubs."""
    remove_generated_files(STUBS_PATH, STUBS_PROTO_PATH)
    generate_python_files(STUBS_PATH, PROTO_PATH, NI_API_PROTO_FILES)
    generate_python_files(STUBS_PATH, STUBS_PROTO_PATH, STUBS_PROTO_FILES)
    fix_import_paths(STUBS_PATH, STUBS_PATH, STUBS_NAMESPACE, PROTO_PARENT_NAMESPACES)
    add_init_files(STUBS_PATH, PROTO_PATH)

    generate_python_files(TEST_STUBS_PATH, TEST_PROTO_PATH, TEST_PROTO_FILES, PROTO_PATH)
    fix_import_paths(TEST_STUBS_PATH, STUBS_PATH, STUBS_NAMESPACE, PROTO_PARENT_NAMESPACES)


def is_relative_to(path: pathlib.PurePath, other: pathlib.PurePath) -> bool:
    """Return whether or not this path is relative to the other path."""
    try:
        path.relative_to(other)
        return True
    except ValueError:
        return False


def remove_generated_files(stubs_path: pathlib.Path, proto_path: pathlib.Path):
    """Remove files generated by protoc."""
    for path in stubs_path.glob("*.py"):
        path.unlink()

    for path in stubs_path.iterdir():
        if not is_relative_to(path, proto_path):
            shutil.rmtree(path, ignore_errors=True)


def generate_python_files(
    stubs_path: pathlib.Path,
    proto_path: pathlib.Path,
    proto_files: Sequence[pathlib.Path],
    alternate_proto_path: pathlib.Path = "",
):
    """Generate python files from .proto files with protoc."""
    arguments = [
        "protoc",
        f"--proto_path={str(proto_path)}",
        f"--proto_path={str(STUBS_PROTO_PATH)}",
        f"--proto_path={pkg_resources.resource_filename('grpc_tools', '_proto')}",
        f"--python_out={str(stubs_path)}",
        f"--mypy_out={str(stubs_path)}",
        f"--grpc_python_out={str(stubs_path)}",
        f"--mypy_grpc_out={str(stubs_path)}",
    ]
    if alternate_proto_path != "":
        arguments += (f"--proto_path={str(alternate_proto_path)}",)

    arguments += [str(path.relative_to(proto_path)).replace("\\", "/") for path in proto_files]

    grpc_tools.protoc.main(arguments)


def fix_import_paths(
    protos_path: pathlib.Path,
    stubs_path: pathlib.Path,
    stubs_namespace: str,
    proto_parent_namespaces: Sequence[str],
):
    """Fix import paths of generated files."""
    print("Fixing import paths")
    grpc_codegened_file_paths = list(protos_path.rglob("*pb2*py"))
    stubs_codegened_file_paths = list(stubs_path.rglob("*pb2*py"))
    imports_to_fix = [path.stem for path in stubs_codegened_file_paths if path.parent == stubs_path]
    imports_to_alias = [
        ".".join(path.relative_to(stubs_path).with_suffix("").parts)
        for path in stubs_codegened_file_paths
        if path.stem not in imports_to_fix
    ]
    grpc_codegened_file_paths.extend(protos_path.rglob("*pb2*pyi"))
    for path in grpc_codegened_file_paths:
        print(f"Processing {path}")
        data = path.read_bytes()
        for name in imports_to_fix:
            data = data.replace(
                f"import {name}".encode(), f"from {stubs_namespace} import {name}".encode()
            )
        for namespace in proto_parent_namespaces:
            data = data.replace(
                f"from {namespace}".encode(),
                f"from {stubs_namespace}.{namespace}".encode(),
            )
        if path.suffix == ".pyi":
            for name in imports_to_alias:
                alias = name.replace(".", "_")
                data = data.replace(
                    f"import {name}\n".encode(),
                    f"import {stubs_namespace}.{name} as {alias}\n".encode(),
                )
                data = data.replace(
                    f"{name}.".encode(),
                    f"{alias}.".encode(),
                )
        path.write_bytes(data)


def add_init_files(stubs_path: pathlib.Path, proto_path: pathlib.Path):
    """Add __init__.py files to generated file directories."""
    for dir in stubs_path.rglob(""):
        if not is_relative_to(dir, proto_path) and dir.is_dir():
            init_path = dir / "__init__.py"
            print(f"Creating {init_path}")
            init_path.write_bytes(b'"""Auto generated gRPC files."""\n')


if __name__ == "__main__":
    main()
