"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Configurations(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PIN_NAME_FIELD_NUMBER: builtins.int
    MEASUREMENT_TYPE_FIELD_NUMBER: builtins.int
    RANGE_FIELD_NUMBER: builtins.int
    RESOLUTION_DIGITS_FIELD_NUMBER: builtins.int
    pin_name: builtins.str
    measurement_type: builtins.int
    """really an enum"""
    range: builtins.float
    resolution_digits: builtins.float
    def __init__(
        self,
        *,
        pin_name: builtins.str = ...,
        measurement_type: builtins.int = ...,
        range: builtins.float = ...,
        resolution_digits: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["measurement_type", b"measurement_type", "pin_name", b"pin_name", "range", b"range", "resolution_digits", b"resolution_digits"]) -> None: ...

global___Configurations = Configurations

@typing_extensions.final
class Outputs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MEASURED_VALUE_FIELD_NUMBER: builtins.int
    SIGNAL_OUT_OF_RANGE_FIELD_NUMBER: builtins.int
    ABSOLUTE_RESOLUTION_FIELD_NUMBER: builtins.int
    measured_value: builtins.float
    signal_out_of_range: builtins.bool
    absolute_resolution: builtins.float
    def __init__(
        self,
        *,
        measured_value: builtins.float = ...,
        signal_out_of_range: builtins.bool = ...,
        absolute_resolution: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["absolute_resolution", b"absolute_resolution", "measured_value", b"measured_value", "signal_out_of_range", b"signal_out_of_range"]) -> None: ...

global___Outputs = Outputs
