#!/usr/bin/env python3
"""Generates gRPC Python stubs from proto files."""

import itertools
import pathlib
import shutil
from typing import List

import black
import grpc_tools.protoc
import pkg_resources
from black.mode import Mode


STUBS_NAMESPACE = "ni_measurement_service._internal.stubs"
PROTO_PARENT_NAMESPACE = "ni.measurementlink"
STUBS_PATH = pathlib.Path(__file__).parent.parent / STUBS_NAMESPACE.replace(".", "/")
PROTO_PATH = STUBS_PATH / "proto"
PROTO_FILES = list(PROTO_PATH.rglob("*.proto"))

TEST_STUBS_PATH = pathlib.Path(__file__).parent.parent / "tests" / "assets"
TEST_PROTO_PATH = TEST_STUBS_PATH
TEST_PROTO_FILES = list(TEST_PROTO_PATH.rglob("*.proto"))


def main():
    """Generate and fixup gRPC Python stubs."""
    remove_generated_files(STUBS_PATH)
    generate_python_files(STUBS_PATH, PROTO_PATH, PROTO_FILES)
    fix_import_paths(STUBS_PATH, STUBS_NAMESPACE, PROTO_PARENT_NAMESPACE)
    add_init_files(STUBS_PATH)
    blacken_code(STUBS_PATH)

    generate_python_files(TEST_STUBS_PATH, TEST_PROTO_PATH, TEST_PROTO_FILES)
    blacken_code(TEST_STUBS_PATH)


def remove_generated_files(stubs_path: pathlib.PurePath):
    """Remove files generated by protoc."""
    for path in stubs_path.glob("*.py"):
        path.unlink()
    shutil.rmtree(stubs_path / "ni", ignore_errors=True)


def generate_python_files(
    stubs_path: pathlib.PurePath, proto_path: pathlib.PurePath, proto_files: List[pathlib.PurePath]
):
    """Generate python files from .proto files with protoc."""
    arguments = [
        "protoc",
        f"--proto_path={str(proto_path)}",
        f"--proto_path={pkg_resources.resource_filename('grpc_tools', '_proto')}",
        f"--python_out={str(stubs_path)}",
        f"--mypy_out={str(stubs_path)}",
        f"--grpc_python_out={str(stubs_path)}",
    ]
    arguments += [str(path.relative_to(proto_path)).replace("\\", "/") for path in proto_files]

    grpc_tools.protoc.main(arguments)


def fix_import_paths(
    stubs_path: pathlib.PurePath, stubs_namespace: str, proto_parent_namespace: str
):
    """Fix import paths of generated files."""
    print("Fixing import paths")
    grpc_codegened_file_paths = list(stubs_path.rglob("*pb2*py"))
    imports_to_fix = [path.stem for path in grpc_codegened_file_paths if path.parent == stubs_path]
    for path in grpc_codegened_file_paths:
        print(f"Processing {path}")
        data = path.read_bytes()
        if path.parent == stubs_path:
            for name in imports_to_fix:
                data = data.replace(
                    f"import {name}".encode(), f"from {stubs_namespace} import {name}".encode()
                )

        data = data.replace(
            f"from {proto_parent_namespace}".encode(),
            f"from {stubs_namespace}.{proto_parent_namespace}".encode(),
        )
        path.write_bytes(data)


def add_init_files(stubs_path: pathlib.PurePath):
    """Add __init__.py files to generated file directories."""
    for dir in itertools.chain([stubs_path], (stubs_path / "ni").rglob("")):
        if dir.is_dir():
            init_path = dir / "__init__.py"
            print(f"Creating {init_path}")
            init_path.write_bytes(b'"""Auto generated gRPC files."""\n')


def blacken_code(stubs_path: pathlib.PurePath):
    """Run black on generated files."""
    print("Running black")
    for py_path in itertools.chain(stubs_path.rglob("*.py"), stubs_path.rglob("*.pyi")):
        if black.format_file_in_place(
            src=py_path, fast=False, mode=Mode(line_length=100), write_back=black.WriteBack.YES
        ):
            print(f"reformatted {py_path}")


if __name__ == "__main__":
    main()
