[tool.poetry]
name = "ni_measurement_plugin_sdk_generator"
version = "2.2.0-dev0"
description = "Measurement Plug-In Code Generator for Python"
authors = ["NI <opensource@ni.com>"]
readme = "README.md"
repository = "https://github.com/ni/measurementlink-python/"
license = "MIT"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Manufacturing",
    "Intended Audience :: Science/Research",
    "Operating System :: Microsoft :: Windows",
    # Poetry automatically adds classifiers for the license and the supported Python versions.
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Topic :: System :: Hardware",
]

[tool.poetry.dependencies]
python = "^3.8"
Mako = "^1.2.1"
click = ">=8.1.3"
grpcio = "^1.49.1"
protobuf = "^4.21"
black = ">=24.8.0"
click-option-group = ">=0.5.6"
ni-measurement-plugin-sdk-service = {version = "^2.1.0"}

[tool.poetry.group.dev.dependencies]
pytest = ">=7.2.0"
pytest-cov = ">=3.0.0"
ni-python-styleguide = ">=0.4.1"
mypy = ">=1.0"
mypy-protobuf = ">=3.4"
types-protobuf = "^4.21"
grpc-stubs = "^1.53"
# During development, use file paths to reference the latest source for packages
# in the same Git repository.
ni-measurement-plugin-sdk-service = {path = "../../packages/service", develop = true}
bandit = { version = ">=1.7", extras = ["toml"] }
tox = ">=4.0"
grpcio-tools = [
  {version = "1.49.1", python = ">=3.8,<3.12"},
  {version = "1.59.0", python = "^3.12"},
]

[tool.poetry.scripts]
ni-measurement-plugin-generator = "ni_measurement_plugin_sdk_generator.plugin:create_measurement"
ni-measurement-plugin-client-generator = "ni_measurement_plugin_sdk_generator.client:create_client"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
extend_exclude = '\.tox/|_pb2(_grpc)?\.(py|pyi)$'
line-length = 100

[tool.ni-python-styleguide]
extend_exclude = '.tox/,*_pb2_grpc.py,*_pb2_grpc.pyi,*_pb2.py,*_pb2.pyi'

[tool.mypy]
files = "ni_measurement_plugin_sdk_generator/,tests/"
exclude = "^tests/test_assets/"
disallow_untyped_defs = true
namespace_packages = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "mako.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
# mypy-protobuf codegen has some unused ignores.
module = "tests.utilities.measurements.non_streaming_data_measurement._stubs.*"
warn_unused_ignores = false

[tool.pytest.ini_options]
addopts = "--doctest-modules --ignore tests/test_assets --strict-markers"
filterwarnings = ["always::ImportWarning", "always::ResourceWarning"]
testpaths = ["tests"]

[tool.bandit]
skips = [
  "B101", # assert_used
  "B702", # use_of_mako_templates
]