# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServiceManagement.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="ServiceManagement.proto",
    package="ni.measurements.servicemanagement.v1",
    syntax="proto3",
    serialized_options=b"\252\0029NationalInstruments.MeasurementServices.ServiceManagement",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x17ServiceManagement.proto\x12$ni.measurements.servicemanagement.v1"\x14\n\x12StopServiceRequest"\x15\n\x13StopServiceResponse2\x9f\x01\n\x18ServiceManagementService\x12\x82\x01\n\x0bStopService\x12\x38.ni.measurements.servicemanagement.v1.StopServiceRequest\x1a\x39.ni.measurements.servicemanagement.v1.StopServiceResponseB<\xaa\x02\x39NationalInstruments.MeasurementServices.ServiceManagementb\x06proto3',
)


_STOPSERVICEREQUEST = _descriptor.Descriptor(
    name="StopServiceRequest",
    full_name="ni.measurements.servicemanagement.v1.StopServiceRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=65,
    serialized_end=85,
)


_STOPSERVICERESPONSE = _descriptor.Descriptor(
    name="StopServiceResponse",
    full_name="ni.measurements.servicemanagement.v1.StopServiceResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=87,
    serialized_end=108,
)

DESCRIPTOR.message_types_by_name["StopServiceRequest"] = _STOPSERVICEREQUEST
DESCRIPTOR.message_types_by_name["StopServiceResponse"] = _STOPSERVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StopServiceRequest = _reflection.GeneratedProtocolMessageType(
    "StopServiceRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _STOPSERVICEREQUEST,
        "__module__": "ServiceManagement_pb2"
        # @@protoc_insertion_point(class_scope:ni.measurements.servicemanagement.v1.StopServiceRequest)
    },
)
_sym_db.RegisterMessage(StopServiceRequest)

StopServiceResponse = _reflection.GeneratedProtocolMessageType(
    "StopServiceResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _STOPSERVICERESPONSE,
        "__module__": "ServiceManagement_pb2"
        # @@protoc_insertion_point(class_scope:ni.measurements.servicemanagement.v1.StopServiceResponse)
    },
)
_sym_db.RegisterMessage(StopServiceResponse)


DESCRIPTOR._options = None

_SERVICEMANAGEMENTSERVICE = _descriptor.ServiceDescriptor(
    name="ServiceManagementService",
    full_name="ni.measurements.servicemanagement.v1.ServiceManagementService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=111,
    serialized_end=270,
    methods=[
        _descriptor.MethodDescriptor(
            name="StopService",
            full_name="ni.measurements.servicemanagement.v1.ServiceManagementService.StopService",
            index=0,
            containing_service=None,
            input_type=_STOPSERVICEREQUEST,
            output_type=_STOPSERVICERESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_SERVICEMANAGEMENTSERVICE)

DESCRIPTOR.services_by_name["ServiceManagementService"] = _SERVICEMANAGEMENTSERVICE

# @@protoc_insertion_point(module_scope)
