"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import google.protobuf.descriptor
import google.protobuf.message

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class StopServiceRequest(google.protobuf.message.Message):
    """Stop Measurement service request - Can add fields in future as required"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

global___StopServiceRequest = StopServiceRequest

class StopServiceResponse(google.protobuf.message.Message):
    """Stop Measurement service response - Can add fields in future as required"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

global___StopServiceResponse = StopServiceResponse
