# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServiceLocation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="ServiceLocation.proto",
    package="ni.measurements.discovery.v1",
    syntax="proto3",
    serialized_options=b"\252\0021NationalInstruments.MeasurementServices.Discovery",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x15ServiceLocation.proto\x12\x1cni.measurements.discovery.v1"q\n\x0fServiceLocation\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x15\n\roptimal_route\x18\x02 \x01(\t\x12\x15\n\rinsecure_port\x18\x03 \x01(\t\x12\x1e\n\x16ssl_authenticated_port\x18\x04 \x01(\tB4\xaa\x02\x31NationalInstruments.MeasurementServices.Discoveryb\x06proto3',
)


_SERVICELOCATION = _descriptor.Descriptor(
    name="ServiceLocation",
    full_name="ni.measurements.discovery.v1.ServiceLocation",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="location",
            full_name="ni.measurements.discovery.v1.ServiceLocation.location",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="optimal_route",
            full_name="ni.measurements.discovery.v1.ServiceLocation.optimal_route",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="insecure_port",
            full_name="ni.measurements.discovery.v1.ServiceLocation.insecure_port",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="ssl_authenticated_port",
            full_name="ni.measurements.discovery.v1.ServiceLocation.ssl_authenticated_port",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=55,
    serialized_end=168,
)

DESCRIPTOR.message_types_by_name["ServiceLocation"] = _SERVICELOCATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceLocation = _reflection.GeneratedProtocolMessageType(
    "ServiceLocation",
    (_message.Message,),
    {
        "DESCRIPTOR": _SERVICELOCATION,
        "__module__": "ServiceLocation_pb2"
        # @@protoc_insertion_point(class_scope:ni.measurements.discovery.v1.ServiceLocation)
    },
)
_sym_db.RegisterMessage(ServiceLocation)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
