# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ServiceManagement.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class StopServiceRequest(betterproto.Message):
    """
    Stop Measurement service request - Can add fields in future as required
    """

    pass


@dataclass
class StopServiceResponse(betterproto.Message):
    """
    Stop Measurement service response - Can add fields in future as required
    """

    pass


class ServiceManagementServiceStub(betterproto.ServiceStub):
    """Service that contains methods related to service management"""

    async def stop_service(self) -> StopServiceResponse:
        """API to stop the measurement service"""

        request = StopServiceRequest()

        return await self._unary_unary(
            "/ni.measurements.servicemanagement.v1.ServiceManagementService/StopService",
            request,
            StopServiceResponse,
        )
