name: Check NIMS Docs

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check_nims:
    name: Check NIMS Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        # Set the working-directory for all steps in this job.
        working-directory: ./packages/service
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false
      - name: Set up Python
        uses: ni/python-actions/setup-python@a2554c7e5680982d3355677b2290e48b60678744 # v0.8.0
        id: setup-python
      - name: Set up Poetry
        uses: ni/python-actions/setup-poetry@a2554c7e5680982d3355677b2290e48b60678744 # v0.8.0
      - name: Install ni-measurement-plugin-sdk-service (all extras, docs)
        run: poetry install -v --all-extras --with docs
      - name: Build docs and check for errors/warnings
        run: |
          rm -rf docs
          mkdir -p docs   
          poetry run sphinx-build _docs_source docs -b html -W
      - name: Revert docs
        run:  rm -rf docs
